image: beagle/ubuntu-build-image

build:
  stage: build
  before_script:
    - sudo apt install -y --no-install-recommends build-essential devscripts debhelper cmake git libarchive-dev libcurl4-gnutls-dev
           qtbase5-dev qtbase5-dev-tools qtdeclarative5-dev libqt5svg5-dev qttools5-dev libgnutls28-dev
           qml-module-qtquick2 qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qtquick-templates2
           qml-module-qtquick-window2 qml-module-qtgraphicaleffects
  script:
    - debuild -uc -us
    - mkdir -p build
    - cp *.deb build
  artifacts:
    paths:
      - build
